title: Sol Gago
baseurl: "/portafolio"
logo: "{{ site.baseurl }}/img/222-Photoroom.jpg"
#description: text below image
#show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
